repository:
    path: github.com/arsonistgopher/influxdb_exporter
build:
    flags: -a -tags netgo
    ldflags: |
        -X {{repoPath}}/vendor/github.com/arsonistgopher/common/version.Version={{.Version}}
        -X {{repoPath}}/vendor/github.com/arsonistgopher/common/version.Revision={{.Revision}}
        -X {{repoPath}}/vendor/github.com/arsonistgopher/common/version.Branch={{.Branch}}
        -X {{repoPath}}/vendor/github.com/arsonistgopher/common/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/vendor/github.com/arsonistgopher/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - NOTICE
